apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres_password"
  JWT_SECRET: "mySecretKeyForJWTAuthTokenGenerationMustBeLongEnough"
